### ISSUE TITLE
Design Dashboard

### ISSUE THREAD

**Issue by aronvdl** [MeesterDaaf/elo#22]
Bij het overzicht van modules in het studentendashboard worden de blokken onoverzichtelijk als er veel tags onder de modulenamen verschijnen.

**Comment by MeesterDaaf** [comment]
Dus jou voorstel is om geen tags daarin te hangen?

**Comment by aronvdl** [comment]
Het zou daar wel kunnen, maar als het er heel veel worden, worden de blokken denk ik onoverzichtelijk. Wat misschien logischer is, is om de tags in het overzichtsscherm te plaatsen van een module. Eventueel ook in de lijst met taken per taak. Op die manier weet een student waar hij aan gaat beginnen.

**Comment by MeesterDaaf** [comment]
Valerie zal deze week een redesign doen van het dashboard, daarbij rekenign houdend met de inforamtie
