### ISSUE TITLE
foutmelding retrieve all modules and tasks (gitHub connectie is aanwezig)

### ISSUE THREAD

**Issue by vvdlinden** [MeesterDaaf/elo#35]
De taken worden wel in de database gezet.
![image](https://user-images.githubusercontent.com/46783993/79978475-470eaf80-84a0-11ea-80af-ded5a829ecef.png)

**Comment by MeesterDaaf** [comment]
Ik vermoed dat dit te maken heeft met de uptime van github die de laatste dagen niet optimaal is,
