### ISSUE TITLE
Modules open/close/done werkt niet meer bij users in eagledev.nl

### ISSUE THREAD

**Issue by vvdlinden** [MeesterDaaf/elo#50]
![image](https://user-images.githubusercontent.com/46783993/81059438-b63cc880-8ed0-11ea-8527-89f98d3de5e7.png)

**Comment by MeesterDaaf** [comment]
Ik kan het niet reproduceren.

**Comment by vvdlinden** [comment]
Vreemd de test heb ik gedaan bij student valerie en ik wil php advanced open zetten. sowieso zie je dat de kleuren niet goed meegaan met de radiobuttons, ik zal later even de edits binnen halen om te kijken of ik het lokaal kan reproduceren, maar misschien kan jij eens testen of jij wel bij student valerie php advanced open kan zetten.

**Comment by MeesterDaaf** [comment]
Getest. Doet het bij mij: 
![image](https://user-images.githubusercontent.com/40887850/81066738-dcb53080-8edd-11ea-8e13-3e15afe8a8bc.png)

**Comment by MeesterDaaf** [comment]
Ik gebruik firefox

**Comment by vvdlinden** [comment]
Ik gebruik Chrome. Krijg geen error in de console...

**Comment by vvdlinden** [comment]
Ik zie het al het werkt wel als je de role admin hebt maar niet als teacher

**Comment by MeesterDaaf** [comment]
fixt it!
