### ISSUE TITLE
PHP-EXPERT-NIVEAU2-Taak04 - Opdracht

### ISSUE THREAD

**Issue by jkhb64** [MeesterDaaf/elo#52]
De opdracht zou voor mij betekenisvoller zijn als de InhoudTank weergegeven zou worden in percentages. Nu kun je een soort discussie krijgen: '6' is dat vol,  leeg of er iets tussenin. Bij 6% zou iedereen zeggen dat hij bijna leeg is. Zo is de opdracht m.i. ook minder abstract.

        Maak een class Scooter
        Geef de Scooter class de volgende properties: kleur, merk, inhoudTank
        Maak twee objecten aan: $piago en $peugeot.
        Geef de properties van de objecten waardes:

        $piago: merk="piago", kleur="rood", inhoudTank="6"
        $peugeot: merk="peugeot", kleur="zwart", inhoudTank="7"

        Maak in de class nu een method aan die checkt of de brandstoftank leeg is. Zo ja, zet een string op het scherm voor ieder object!

**Comment by MeesterDaaf** [comment]
De commentaren mbt de opdrachten kun je het beste kwijt bij de repo van de module zelf
