### ISSUE TITLE
Voeg visuele feedback toe na status change van task

### ISSUE THREAD

**Issue by spectrapulse** [MeesterDaaf/elo#67]
## Het veranderen van de status van een taak geeft in geen enkele manier door of deze verandering wel werkelijk gemaakt is.

**To Reproduce:**
Dashboard > Selecteer een Module > Selecteer een taak > Verander de status van de taak (Bezig/Afgerond)

**Current Behavior:**
De status change word gesubmit maar de gebruiker krijgt geen feedback of deze change werkelijk gemaakt is en moet terug naar taken overzicht om te kijken of de status veranderd is.

**Expected Behavior:**
Gebruiker krijgt bevestiging op zelfde pagina dat de verandering op de status is aangebracht.

**Comment by MeesterDaaf** [comment]
Done
