### ISSUE TITLE
[ENHANCEMENT] Geef clone link naar gecreëerde repo op module pagina

### ISSUE THREAD

**Issue by spectrapulse** [MeesterDaaf/elo#68]
Op dit moment om je repo te clonen na het openen van een module moet je inloggen op GitHub en dan tussen je eigen repositories zoeken naar de juiste. Dit kan tijd kosten. 

Het lijkt mij handiger als er op de pagina van de module zelf een knop of een textbox is waar je de link krijgt om met SSH te clonen of naar de repo op github kan gaan om daar de SSH link te krijgen om te clonen.

**Comment by MeesterDaaf** [comment]
Gefixt. Komt met de volgende versie
