### ISSUE TITLE
nieuwste verzoeken bovenaan en voltooid eruit

### ISSUE THREAD

**Issue by dedaaf** [MeesterDaaf/elo#69]

**Comment by vvdlinden** [comment]
Ik zou wel een archief aanhouden voor als je een afgehandeld verzoek zou moeten bekijken, dus dat hij standaard staat op verborgen maar dat je er wel op kan filteren (nice to have)

**Comment by aavroc** [comment]
Dit is gefixed doordat er in de tabel kan worden gefilterd?
