### ISSUE TITLE
Bij sommige studenten blijft staan nooit ingelogd geweest...

### ISSUE THREAD

**Issue by vvdlinden** [MeesterDaaf/elo#72]
Zie bijvoorbeeld Tygo Egmond, die heeft zijn module opracht afgerond maar staat in mijn dashboard als nooit ingelogd geweest, hetzelfde had ik met pricilla (9D), die staat inmiddels wel goed.

**Comment by MeesterDaaf** [comment]
Als ze nog een keer inloggen dan moet het  goed gaan. Waarom het niet geregistreerd werd is mij een raadsel
